Repository kartoza/miniSASS, pull requests merged in 2023-12, with the labels that each got.

#318 Bug fixes
  django_project/minisass/admin.py
  django_project/minisass/models.py
  django_project/minisass_authentication/templates/registration/contact_us.html
  django_project/minisass_authentication/views.py
  django_project/minisass_frontend/src/components/ContactFormModal/index.tsx
  django_project/minisass_frontend/src/components/ScoreForm/index.tsx
Labels: front-end

#320 Fix registration
  django_project/minisass_authentication/email_verification_token.py
  django_project/minisass_authentication/templates/registration/activate.html
  django_project/minisass_authentication/templates/registration/activate_account.html
  django_project/minisass_authentication/templates/registration/activation_complete.html
  django_project/minisass_authentication/templates/registration/activation_email.txt
  django_project/minisass_authentication/templates/registration/activation_email_subject.txt
  django_project/minisass_authentication/test_views.py
  django_project/minisass_authentication/tests.py
  django_project/minisass_authentication/urls.py
  django_project/minisass_authentication/views.py
  django_project/minisass_frontend/src/components/AuthenticationButtons/index.tsx
  django_project/minisass_frontend/src/components/RegistrationFormModal/index.tsx
  django_project/minisass_frontend/src/pages/MainPage/index.tsx
Labels: back-end

#329 Reset password implementation
  django_project/minisass_authentication/templates/registration/password_reset_email.html
  django_project/minisass_authentication/test_views.py
  django_project/minisass_authentication/urls.py
  django_project/minisass_authentication/views.py
  django_project/minisass_frontend/src/components/ForgotPasswordForm/index.tsx
  django_project/minisass_frontend/src/components/PasswordResetForm/index.tsx
  django_project/minisass_frontend/src/pages/MainPage/index.tsx
  django_project/minisass_frontend/src/pages/PasswordReset/index.tsx
Labels: front-end, back-end

#325 Observation api documentation
  docs/mkdocs-base.yml
  docs/src/developer/img/crud_observations.png
  docs/src/developer/img/observation_details.png
  docs/src/developer/img/recent_observations.png
  docs/src/developer/index.md
  docs/src/developer/observations.md
Labels: Documentation

#289 Add setting up documentation
  docs/src/developer/install.md
Labels: Documentation

#323 Sites api documentation
  docs/mkdocs-base.yml
  docs/src/developer/img/site_crud_api.png
  docs/src/developer/img/sites_api.png
  docs/src/developer/index.md
  docs/src/developer/sites.md
Labels: Documentation

#349 Enforce correct behaviour on satellite switch
  django_project/minisass_frontend/src/components/Map/Layer/Basemap.tsx
  django_project/minisass_frontend/src/components/Map/Layer/Selector.tsx
  django_project/minisass_frontend/src/components/Map/Map.tsx
  django_project/minisass_frontend/src/pages/Map/index.tsx
Labels: front-end

#350 Fix missing logo in email and invalid reset link
  django_project/minisass_authentication/templates/registration/activate_account.html
  django_project/minisass_authentication/templates/registration/contact_us.html
  django_project/minisass_authentication/templates/registration/password_reset_email.html
  django_project/minisass_authentication/views.py
  django_project/minisass_frontend/src/pages/MainPage/index.tsx
Labels: front-end, back-end

#351 patch: add some password constraints
  django_project/minisass_frontend/src/components/RegistrationFormModal/index.tsx
Labels: front-end

#353 Fix group scores
  django_project/minisass/migrations/0001_initial.py
  django_project/minisass/migrations/0002_groupscores.py
  django_project/minisass/migrations/0003_alter_groupscores_id.py
Labels: back-end

#345 UI fixes 2
  django_project/minisass_frontend/src/components/AuthenticationButtons/index.tsx
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
  django_project/minisass_frontend/src/components/PasswordResetForm/index.tsx
  django_project/minisass_frontend/src/components/RegistrationFormModal/index.tsx
  django_project/minisass_frontend/src/components/ScoreForm/index.tsx
Labels: front-end

#359 patch: show formatted date
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
Labels: front-end

#361 patch: update handling of password constraints
  django_project/minisass_frontend/src/components/RegistrationFormModal/index.tsx
Labels: front-end

#360 UI fixes 3
  django_project/minisass_frontend/src/Routes.tsx
  django_project/minisass_frontend/src/components/ContactFormModal/index.tsx
  django_project/minisass_frontend/src/pages/MainPage/index.tsx
Labels: front-end

#362 Fix logo not showing in email templates
  django_project/minisass_authentication/templates/registration/activate_account.html
  django_project/minisass_authentication/templates/registration/contact_us.html
  django_project/minisass_authentication/templates/registration/password_reset_email.html
  django_project/minisass_authentication/views.py
Labels: front-end

#384 Update add record form
  django_project/minisass_frontend/src/components/CoordinatesInputForm/index.tsx
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
  django_project/minisass_frontend/src/components/Map/Map.tsx
  django_project/minisass_frontend/src/components/ScoreForm/index.tsx
  django_project/minisass_frontend/src/components/Sidebar/index.tsx
  django_project/minisass_frontend/src/pages/Map/index.tsx
Labels: front-end

#352 Add expert field on user profile
  django_project/minisass_authentication/admin.py
  django_project/minisass_authentication/migrations/0005_userprofile_is_expert.py
  django_project/minisass_authentication/models.py
Labels: back-end

#375 patch: pass parameters correctly
  django_project/minisass_authentication/views.py
  django_project/minisass_frontend/src/components/ObservationDetails/index.tsx
  django_project/minisass_frontend/src/components/ScoreForm/index.tsx
  django_project/monitor/observation_views.py
Labels: front-end, back-end

#376 Fetch site observations
  django_project/monitor/serializers.py
  django_project/monitor/site_views.py
  django_project/monitor/test_sites.py
  django_project/monitor/urls.py
Labels: back-end

#385 Add assessment model and relationships
  django_project/monitor/admin.py
  django_project/monitor/migrations/0004_assessment_observations_minisass_ml_score_and_more.py
  django_project/monitor/models.py
  django_project/monitor/serializers.py
  django_project/monitor/site_views.py
  django_project/monitor/tests/test_assessments.py
  django_project/monitor/urls.py
Labels: back-end

#390 fix bug
  django_project/monitor/serializers.py
Labels: bug

#383 Update observation docs
  docs/src/developer/img/fetching_images_for_observation.png
  docs/src/developer/img/site_images.png
  docs/src/developer/observations.md
Labels: Documentation

#404 Fix registration error
  django_project/minisass_authentication/serializers.py
  django_project/minisass_authentication/views.py
Labels: bug

#406 Create registration status api
  django_project/minisass_authentication/urls.py
  django_project/minisass_authentication/views.py
Labels: back-end

#405 Fix save datainput form
  django_project/minisass_frontend/src/components/ScoreForm/index.tsx
  django_project/monitor/observation_views.py
Labels: bug

#407 Fetch observations by site
  django_project/monitor/observation_views.py
  django_project/monitor/serializers.py
  django_project/monitor/tests/test_observations.py
  django_project/monitor/urls.py
Labels: back-end

#408 feat: ovveride default site create view
  django_project/monitor/site_views.py
  django_project/monitor/test_sites.py
  django_project/monitor/tests/test_sites.py
Labels: back-end

#414 patch: add missing imports
  django_project/minisass/settings.py
  django_project/monitor/observation_views.py
Labels: bug

#374 Observation information panel for sites
  django_project/minisass_frontend/src/components/Map/Map.tsx
  django_project/minisass_frontend/src/components/ObservationDetails/index.tsx
  django_project/minisass_frontend/src/components/Sidebar/index.tsx
  django_project/minisass_frontend/src/components/TabbedContent/index.tsx
  django_project/minisass_frontend/src/pages/Map/index.tsx
Labels: front-end

#421 Fixes 5
  django_project/minisass_frontend/src/components/Map/Map.tsx
  django_project/minisass_frontend/src/components/ObservationDetails/index.tsx
Labels: bug

#423 check condition before assigning values
  django_project/minisass_frontend/src/components/ObservationDetails/index.tsx
  django_project/monitor/site_views.py
Labels: bug

#424 Fixes 6
  django_project/minisass_frontend/src/components/Map/Map.tsx
  django_project/monitor/site_views.py
Labels: bug

#428 Create manual structure
  docs/src/manual/contact-us.md
  docs/src/manual/how-to/index.md
  docs/src/manual/index.md
  docs/src/manual/landing-page.md
  docs/src/manual/login-logout/index.md
  docs/src/manual/map/index.md
  docs/src/manual/register/index.md
  docs/src/manual/user-profile/index.md
Labels: Size: 2, Documentation

#429 patch: update url
  django_project/minisass_frontend/src/components/Map/Map.tsx
Labels: front-end

#431 patch: pass long and lat as variables
  django_project/minisass_frontend/src/components/Map/Map.tsx
Labels: bug

#433 patch: declare tabs data as an array
  django_project/minisass_frontend/src/components/ObservationDetails/index.tsx
Labels: bug

#434 patch: test custom add tabs
  django_project/minisass_frontend/src/components/ObservationDetails/index.tsx
Labels: front-end

#435 patch: prevent opening observation details if site observations is null
  django_project/minisass_frontend/src/pages/Map/index.tsx
Labels: front-end

#436 patch: show multiple tabs for sites with multiple observations
  django_project/minisass_frontend/src/components/ObservationDetails/index.tsx
Labels: front-end

#437 Set default choice on rivercategory
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
  django_project/monitor/observation_views.py
Labels: bug

#439 patch: count users
  django_project/minisass_authentication/views.py
Labels: bug

#440 patch: prevent integrity error
  django_project/monitor/observation_views.py
Labels: bug

#441 patch: remove test for now
  django_project/minisass_authentication/test_views.py
Labels: bug

#442 resolve unknown field error
  django_project/minisass_authentication/views.py
Labels: bug

#445 Save flag state when creating observation
  django_project/minisass_authentication/serializers.py
  django_project/minisass_authentication/urls.py
  django_project/minisass_authentication/views.py
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
  django_project/minisass_frontend/src/components/ScoreForm/index.tsx
Labels: front-end, back-end

#444 Direct submit results to map page
  django_project/minisass_frontend/src/pages/MainPage/index.tsx
  django_project/minisass_frontend/src/pages/Map/index.tsx
Labels: front-end

#447 patch: fix missing required positional argument
  django_project/minisass_authentication/views.py
Labels: bug

#448 patch integrity error on user profile
  django_project/minisass_authentication/views.py
Labels: bug

#443 Enable select site on map
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
  django_project/minisass_frontend/src/components/Map/Map.tsx
  django_project/minisass_frontend/src/components/Sidebar/index.tsx
  django_project/minisass_frontend/src/pages/Map/index.tsx
Labels: front-end

#449 Fix fetch site by location empty observations
  django_project/monitor/serializers.py
Labels: back-end

#450 prevent user from existing user from being created twice
  django_project/minisass_authentication/serializers.py
  django_project/minisass_authentication/views.py
Labels: bug

#451 Landing page manual
  docs/src/manual/landing-page.md
  docs/src/user/img/naming_convention.README
  docs/src/user/manual/contact-us.md
  docs/src/user/manual/how-to/index.md
  docs/src/user/manual/img/landing-page-1.png
  docs/src/user/manual/img/landing-page-10.png
  docs/src/user/manual/img/landing-page-11.png
  docs/src/user/manual/img/landing-page-12.png
  docs/src/user/manual/img/landing-page-13.png
  docs/src/user/manual/img/landing-page-14.png
  docs/src/user/manual/img/landing-page-15.png
  docs/src/user/manual/img/landing-page-16.png
  docs/src/user/manual/img/landing-page-17.png
  docs/src/user/manual/img/landing-page-18.png
  docs/src/user/manual/img/landing-page-19.png
  docs/src/user/manual/img/landing-page-2.png
  docs/src/user/manual/img/landing-page-3.png
  docs/src/user/manual/img/landing-page-4.png
  docs/src/user/manual/img/landing-page-5.png
  docs/src/user/manual/img/landing-page-6.png
  docs/src/user/manual/img/landing-page-7.png
  docs/src/user/manual/img/landing-page-8.png
  docs/src/user/manual/img/landing-page-9.png
  docs/src/user/manual/index.md
  docs/src/user/manual/landing-page.md
  docs/src/user/manual/login-logout/index.md
  docs/src/user/manual/map/index.md
  docs/src/user/manual/register/index.md
  docs/src/user/manual/upload/index.md
  docs/src/user/manual/user-profile/index.md
Labels: Size: 8, Documentation

#457 patch: fix user undefined error
  django_project/minisass_authentication/serializers.py
Labels: bug

#458 patch: add missing prop
  django_project/minisass_frontend/src/pages/Map/index.tsx
Labels: bug

#465 test source of fail
  django_project/minisass_authentication/views.py
Labels: bug

#466 patch: use user profile update serializer
  django_project/minisass_authentication/views.py
Labels: bug

#468 Add loader to sites
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
  django_project/minisass_frontend/src/pages/Map/index.tsx
Labels: UI

#462 patch: add a horizontal scroll to the tabs
  django_project/minisass_frontend/src/components/TabbedContent/index.tsx
Labels: UI

#470 patch: fix user profile intergrity errors
  django_project/minisass_authentication/views.py
Labels: bug

#475 Tinashechiraya patch 9
  .example.env
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
  django_project/minisass_frontend/src/pages/Map/index.tsx
Labels: bug

#476 remove repetitive function
  django_project/minisass_frontend/src/components/Map/Map.tsx
  django_project/minisass_frontend/src/pages/Map/index.tsx
Labels: bug

#477 prevent integrity errors
  django_project/minisass_authentication/views.py
Labels: bug

#478 disable DMS input
  django_project/minisass_frontend/src/components/CoordinatesInputForm/index.tsx
Labels: UI

#480 Test registration2
  django_project/minisass_authentication/serializers.py
  django_project/minisass_authentication/test_views.py
  django_project/minisass_authentication/views.py
Labels: back-end

#481 patch: check if user has user profile
  django_project/minisass_authentication/views.py
Labels: back-end

#482 patch: add user id on save object
  django_project/minisass_authentication/views.py
Labels: back-end

#483 patch: count the records instead of id
  django_project/minisass_authentication/views.py
Labels: back-end

#486 Add manage images
  django_project/minisass_frontend/src/components/ManageImagesModal/index.tsx
  django_project/minisass_frontend/src/components/ScoreForm/index.tsx
Labels: front-end, UI

#487 declare missing variable
  django_project/minisass_frontend/src/components/ScoreForm/index.tsx
Labels: front-end

#488 Prevent select site on map closing sidebar
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
  django_project/minisass_frontend/src/components/Map/Map.tsx
  django_project/minisass_frontend/src/components/Sidebar/index.tsx
  django_project/minisass_frontend/src/pages/Map/index.tsx
Labels: front-end

#489 patch: adjust tooltips positions
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
Labels: front-end

#490 patch: fix undefined error on sitedetails
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
Labels: front-end

#491 patch: update dms inputs
  django_project/minisass_frontend/src/components/CoordinatesInputForm/index.tsx
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
Labels: front-end

#492 patch: update object
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
Labels: front-end

#493 patch: adjust dms inputs values
  django_project/minisass_frontend/src/components/CoordinatesInputForm/index.tsx
Labels: front-end

#494 patch: update river name variable
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
Labels: front-end

#496 patch: maintain degrees on select location on map
  django_project/minisass_frontend/src/components/CoordinatesInputForm/index.tsx
Labels: front-end

#497 Test images not appearing in emails
  django_project/minisass_authentication/templates/registration/activate_account.html
  django_project/minisass_authentication/templates/registration/contact_us.html
  django_project/minisass_frontend/src/components/ScoreForm/index.tsx
Labels: back-end

#499 make registration form responsive
  django_project/minisass_frontend/src/components/RegistrationFormModal/index.tsx
Labels: front-end

#502 patch: update reset password url
  django_project/minisass_frontend/src/components/PasswordResetForm/index.tsx
Labels: front-end

#503 patch: reduce letters to correct default position
  django_project/minisass_frontend/src/components/RegistrationFormModal/index.tsx
Labels: front-end

#504 patch: remove scrolls
  django_project/minisass_frontend/src/components/RegistrationFormModal/index.tsx
  django_project/minisass_frontend/src/components/TabbedContent/index.tsx
Labels: front-end

#505 patch: update variable
  django_project/monitor/observation_views.py
Labels: back-end

#508 patch: adjust button positions
  django_project/minisass_frontend/src/components/RegistrationFormModal/index.tsx
Labels: UI

#510 patch: fix white page issue after go back
  django_project/minisass_frontend/src/pages/PasswordReset/index.tsx
Labels: front-end

#509 fix sites name not showing in dropdown when selected
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
Labels: front-end

#514 patch: update loader when user is registering
  django_project/minisass_frontend/src/components/AuthenticationButtons/index.tsx
Labels: UI

#515 patch: update url param after success message
  django_project/minisass_frontend/src/pages/MainPage/index.tsx
Labels: front-end

#516 patch: update response message styling
  django_project/minisass_frontend/src/components/ContactFormModal/index.tsx
Labels: front-end

#517 Patch display user related errors
  django_project/minisass_frontend/src/components/AuthenticationButtons/index.tsx
Labels: front-end

#518 patch: add fixed width for password field
  django_project/minisass_frontend/src/components/RegistrationFormModal/index.tsx
Labels: front-end

#519 patch: add loader to forgot password
  django_project/minisass_frontend/src/components/ForgotPasswordForm/index.tsx
Labels: front-end

#521 patch: prevent decimal conversion error on observation save
  django_project/minisass_frontend/src/components/ScoreForm/index.tsx
Labels: bug

#523 patch: disable save button
  django_project/minisass_frontend/src/components/ScoreForm/index.tsx
Labels: front-end

#520 Manual login page
  docs/src/user/manual/login-logout/forgot-password.md
  docs/src/user/manual/login-logout/img/forgot-password-1.png
  docs/src/user/manual/login-logout/img/forgot-password-2.png
  docs/src/user/manual/login-logout/img/forgot-password-3.png
  docs/src/user/manual/login-logout/img/login-1.png
  docs/src/user/manual/login-logout/img/login-2.png
  docs/src/user/manual/login-logout/img/login-3.png
  docs/src/user/manual/login-logout/img/reset-password-email-1.png
  docs/src/user/manual/login-logout/img/reset-password-email-2.png
  docs/src/user/manual/login-logout/img/reset-password-email-4.png
  docs/src/user/manual/login-logout/img/reset-password-email-5.png
  docs/src/user/manual/login-logout/img/reset-password-email-6.png
  docs/src/user/manual/login-logout/login.md
  docs/src/user/manual/login-logout/reset-password-email.md
Labels: Size: 8, Documentation

#525 Manual register page
  docs/src/user/manual/register/activate-account.md
  docs/src/user/manual/register/img/activate-account-1.png
  docs/src/user/manual/register/img/activate-account-2.png
  docs/src/user/manual/register/img/register-1.png
  docs/src/user/manual/register/img/register-2.png
  docs/src/user/manual/register/img/register-3.png
  docs/src/user/manual/register/img/register-4.png
  docs/src/user/manual/register/img/register-5.png
  docs/src/user/manual/register/img/register-6.png
  docs/src/user/manual/register/index.md
  docs/src/user/manual/register/register.md
Labels: Size: 3, Documentation

#527 Manual profile section
  docs/src/user/manual/login-logout/img/logout-1.png
  docs/src/user/manual/login-logout/img/logout-2.png
  docs/src/user/manual/login-logout/logout.md
  docs/src/user/manual/user-profile/img/recent-activity-1.png
  docs/src/user/manual/user-profile/img/recent-activity-2.png
  docs/src/user/manual/user-profile/img/user-profile-1.png
  docs/src/user/manual/user-profile/img/user-profile-2.png
  docs/src/user/manual/user-profile/img/user-profile-3.png
  docs/src/user/manual/user-profile/img/user-profile-4.png
  docs/src/user/manual/user-profile/img/user-profile-5.png
  docs/src/user/manual/user-profile/img/user-profile-6.png
  docs/src/user/manual/user-profile/img/user-profile-7.png
  docs/src/user/manual/user-profile/img/user-profile-8.png
  docs/src/user/manual/user-profile/index.md
  docs/src/user/manual/user-profile/profile.md
  docs/src/user/manual/user-profile/recent-activity.md
Labels: Size: 8, Documentation

#530 Contact page manual
  docs/src/user/manual/contact-us.md
  docs/src/user/manual/img/contact-us-1.png
  docs/src/user/manual/img/contact-us-2.png
  docs/src/user/manual/img/contact-us-3.png
  docs/src/user/manual/img/contact-us-4.png
Labels: Size: 2, Documentation

#531 How to page manual
  docs/src/user/manual/how-to/how-to.md
  docs/src/user/manual/how-to/img/how-to-1.png
  docs/src/user/manual/how-to/img/how-to-10.png
  docs/src/user/manual/how-to/img/how-to-11.png
  docs/src/user/manual/how-to/img/how-to-12.png
  docs/src/user/manual/how-to/img/how-to-13.png
  docs/src/user/manual/how-to/img/how-to-14.png
  docs/src/user/manual/how-to/img/how-to-2.png
  docs/src/user/manual/how-to/img/how-to-3.png
  docs/src/user/manual/how-to/img/how-to-4.png
  docs/src/user/manual/how-to/img/how-to-5.png
  docs/src/user/manual/how-to/img/how-to-6.png
  docs/src/user/manual/how-to/img/how-to-7.png
  docs/src/user/manual/how-to/img/how-to-8.png
  docs/src/user/manual/how-to/img/how-to-9.png
  docs/src/user/manual/landing-page.md
Labels: Size: 5, Documentation
