Repository kartoza/miniSASS, pull requests merged in 2024-10, with the labels that each got.

#1085 patch: add missing import
  django_project/minisass/urls.py
Labels: back-end

#1086 patch: update test results
  django_project/minisass_authentication/tests/test_views.py
Labels: back-end

#1089 Add search tag on sitewithobservations
  django_project/minisass_frontend/src/components/DownloadObservationModal/index.tsx
  django_project/minisass_frontend/src/components/ScoreForm/index.tsx
  django_project/monitor/observation_views.py
  django_project/monitor/site_views.py
Labels: back-end

#1081 Added 3rd party api docs
  docs/src/developer/3rd-party-api-access.md
  docs/src/developer/img/3rd-party-api-access-1.png
  docs/src/developer/img/3rd-party-api-access-10.png
  docs/src/developer/img/3rd-party-api-access-11.png
  docs/src/developer/img/3rd-party-api-access-12.png
  docs/src/developer/img/3rd-party-api-access-13.png
  docs/src/developer/img/3rd-party-api-access-14.png
  docs/src/developer/img/3rd-party-api-access-15.png
  docs/src/developer/img/3rd-party-api-access-16.png
  docs/src/developer/img/3rd-party-api-access-17.png
  docs/src/developer/img/3rd-party-api-access-18.png
  docs/src/developer/img/3rd-party-api-access-19.png
  docs/src/developer/img/3rd-party-api-access-2.png
  docs/src/developer/img/3rd-party-api-access-20.png
  docs/src/developer/img/3rd-party-api-access-21.png
  docs/src/developer/img/3rd-party-api-access-22.png
  docs/src/developer/img/3rd-party-api-access-23.png
  docs/src/developer/img/3rd-party-api-access-24.png
  docs/src/developer/img/3rd-party-api-access-25.png
  docs/src/developer/img/3rd-party-api-access-26.png
  docs/src/developer/img/3rd-party-api-access-27.png
  docs/src/developer/img/3rd-party-api-access-28.png
  docs/src/developer/img/3rd-party-api-access-29.png
  docs/src/developer/img/3rd-party-api-access-3.png
  docs/src/developer/img/3rd-party-api-access-30.png
  docs/src/developer/img/3rd-party-api-access-31.png
  docs/src/developer/img/3rd-party-api-access-32.png
  docs/src/developer/img/3rd-party-api-access-33.png
  docs/src/developer/img/3rd-party-api-access-34.png
  docs/src/developer/img/3rd-party-api-access-35.png
  docs/src/developer/img/3rd-party-api-access-36.png
  docs/src/developer/img/3rd-party-api-access-4.png
  docs/src/developer/img/3rd-party-api-access-5.png
  docs/src/developer/img/3rd-party-api-access-6.png
  docs/src/developer/img/3rd-party-api-access-7.png
  docs/src/developer/img/3rd-party-api-access-8.png
  docs/src/developer/img/3rd-party-api-access-9.png
  docs/src/developer/index.md
Labels: Documentation

#1088 patch: add a tag to allow searching and filtering
  django_project/monitor/site_views.py
Labels: back-end

#1090 patch: add custom url path for observation image view set
  django_project/monitor/urls.py
Labels: back-end

#1091 patch: remove repeating tag
  django_project/monitor/site_views.py
Labels: back-end

#1094 patch: check if observation pk is completely absent
  django_project/monitor/observation_views.py
Labels: back-end

#1095 patch: add missing foward slash
  django_project/minisass_frontend/src/components/UserMenu/index.tsx
Labels: back-end

#1110 Patch use authentication on api
  django_project/monitor/site_views.py
  django_project/monitor/tests/test_sites.py
Labels: back-end

#1112 Update groundtruth logo
  django_project/minisass_frontend/src/components/Footer/index.tsx
  django_project/minisass_frontend/static/images/img_image6.jpg
  django_project/minisass_frontend/static/images/img_image6.png
Labels: front-end

#1116 Remove view
  django_project/minisass/management/commands/generate_token.py
  django_project/minisass_authentication/tests/test_views.py
  django_project/minisass_authentication/urls.py
  django_project/minisass_authentication/views.py
  django_project/monitor/tests/test_sites.py
Labels: back-end

#1117 patch: add missing access token import
  django_project/monitor/tests/test_sites.py
Labels: back-end

#1111 3rd party api update
  docs/src/developer/3rd-party-api-access.md
  docs/src/developer/img/3rd-party-api-access-11.png
  docs/src/developer/img/3rd-party-api-access-2.png
  docs/src/developer/img/3rd-party-api-access-30.png
  docs/src/developer/img/3rd-party-api-access-31.png
  docs/src/developer/img/3rd-party-api-access-32.png
  docs/src/developer/img/3rd-party-api-access-33.png
  docs/src/developer/img/3rd-party-api-access-34.png
Labels: Documentation

#1119 patch: add missing fields
  django_project/monitor/serializers.py
Labels: back-end

#1115 Token authentication 3rd party api
  docs/mkdocs-html.yml
  docs/src/developer/3rd-party-api-access.md
  docs/src/developer/img/3rd-party-api-access-37.png
  docs/src/developer/img/3rd-party-api-access-38.png
  docs/src/developer/img/3rd-party-api-access-39.png
  docs/src/developer/img/3rd-party-api-access-40.png
  docs/src/developer/img/3rd-party-api-access-41.png
  docs/src/developer/img/3rd-party-api-access-42.png
  docs/src/developer/img/3rd-party-api-access-43.png
  docs/src/img/img_minisasslogo1.png
Labels: Documentation

#1039 Documentation change password on first login
  docs/src/user/guide/img/register-login-logout-10.png
  docs/src/user/guide/img/register-login-logout-11.png
  docs/src/user/guide/img/register-login-logout-12.png
  docs/src/user/guide/img/register-login-logout-9.png
  docs/src/user/guide/register-login-logout.md
  docs/src/user/manual/img/landing-page-26.png
  docs/src/user/manual/img/landing-page-27.png
  docs/src/user/manual/img/landing-page-28.png
  docs/src/user/manual/img/landing-page-9.png
  docs/src/user/manual/landing-page.md
Labels: Documentation
