Repository kartoza/miniSASS, pull requests merged in 2024-05, with the labels that each got.

#1000 Upload guide
  docs/mkdocs-base.yml
  docs/src/user/guide/img/upload-1.png
  docs/src/user/guide/img/upload-10.png
  docs/src/user/guide/img/upload-11.png
  docs/src/user/guide/img/upload-12.png
  docs/src/user/guide/img/upload-13.png
  docs/src/user/guide/img/upload-14.png
  docs/src/user/guide/img/upload-15.png
  docs/src/user/guide/img/upload-16.png
  docs/src/user/guide/img/upload-17.png
  docs/src/user/guide/img/upload-18.png
  docs/src/user/guide/img/upload-19.png
  docs/src/user/guide/img/upload-2.png
  docs/src/user/guide/img/upload-3.png
  docs/src/user/guide/img/upload-4.png
  docs/src/user/guide/img/upload-5.png
  docs/src/user/guide/img/upload-6.png
  docs/src/user/guide/img/upload-7.png
  docs/src/user/guide/img/upload-8.png
  docs/src/user/guide/img/upload-9.png
  docs/src/user/guide/index.md
  docs/src/user/guide/upload.md
Labels: Size: 8, Documentation

#1002 Update logout manual
  docs/src/user/guide/register-login-logout.md
  docs/src/user/manual/login-logout/img/logout-3.png
  docs/src/user/manual/login-logout/img/reset-password-email-1.png
  docs/src/user/manual/login-logout/logout.md
  docs/src/user/manual/register/img/activate-account-1.png
  docs/src/user/manual/register/img/register-7.png
  docs/src/user/manual/register/register.md
Labels: Size: 2, Documentation

#1004 Map guide
  docs/mkdocs-base.yml
  docs/src/user/guide/img/map-1.png
  docs/src/user/guide/img/map-10.png
  docs/src/user/guide/img/map-11.png
  docs/src/user/guide/img/map-12.png
  docs/src/user/guide/img/map-13.png
  docs/src/user/guide/img/map-14.png
  docs/src/user/guide/img/map-15.png
  docs/src/user/guide/img/map-16.png
  docs/src/user/guide/img/map-2.png
  docs/src/user/guide/img/map-3.png
  docs/src/user/guide/img/map-4.png
  docs/src/user/guide/img/map-5.png
  docs/src/user/guide/img/map-6.png
  docs/src/user/guide/img/map-7.png
  docs/src/user/guide/img/map-8.png
  docs/src/user/guide/img/map-9.png
  docs/src/user/guide/index.md
  docs/src/user/guide/map.md
Labels: Size: 5, Documentation

#1008 patch: fix typo
  django_project/monitor/site_views.py
Labels: back-end

#1010 patch: remove link
  django_project/minisass_frontend/src/components/Footer/index.tsx
Labels: back-end

#1011 patch: show user first name only on username
  django_project/monitor/observation_views.py
Labels: back-end

#1009 patch: handle multiple users with the same email
  django_project/minisass_authentication/views.py
  django_project/minisass_frontend/src/components/PasswordResetForm/index.tsx
Labels: back-end

#1012 patch: prevent integrity error
  django_project/monitor/site_views.py
Labels: back-end

#1007 Documentation headers
  docs/src/about/index.md
  docs/src/administrator/admin.md
  docs/src/administrator/django-admin.md
  docs/src/administrator/index.md
  docs/src/developer/authentication.md
  docs/src/developer/index.md
  docs/src/developer/install.md
  docs/src/developer/observations.md
  docs/src/developer/profile.md
  docs/src/developer/sites.md
  docs/src/index.md
  docs/src/user/guide/forgot-password.md
  docs/src/user/guide/index.md
  docs/src/user/guide/profile.md
  docs/src/user/guide/register-login-logout.md
  docs/src/user/index.md
  docs/src/user/manual/contact-us.md
  docs/src/user/manual/how-to/how-to.md
  docs/src/user/manual/how-to/index.md
  docs/src/user/manual/index.md
  docs/src/user/manual/landing-page.md
  docs/src/user/manual/login-logout/forgot-password.md
  docs/src/user/manual/login-logout/index.md
  docs/src/user/manual/login-logout/login.md
  docs/src/user/manual/login-logout/logout.md
  docs/src/user/manual/login-logout/reset-password-email.md
  docs/src/user/manual/map/index.md
  docs/src/user/manual/map/map.md
  docs/src/user/manual/map/recent-observation.md
  docs/src/user/manual/register/activate-account.md
  docs/src/user/manual/register/index.md
  docs/src/user/manual/register/register.md
  docs/src/user/manual/upload/add-records.md
  docs/src/user/manual/upload/index.md
  docs/src/user/manual/upload/score.md
  docs/src/user/manual/user-profile/index.md
  docs/src/user/manual/user-profile/profile.md
  docs/src/user/manual/user-profile/recent-activity.md
  docs/src/user/quickstart/index.md
Labels: Documentation

#1014 patch: resolve indentation errors
  django_project/minisass_authentication/views.py
  django_project/monitor/observation_views.py
Labels: back-end

#1015 patch: resolve indentation errors
  django_project/monitor/site_views.py
Labels: back-end

#1013 patch: set every user to is active
  deployment/docker/entrypoint.sh
  django_project/minisass_frontend/src/components/Footer/index.tsx
Labels: Admin

#1017 prevent site crash on null organisation type
  django_project/minisass_frontend/src/components/Map/Map.tsx
Labels: front-end

#1019 patch: adjust null condition
  django_project/minisass_frontend/src/components/Map/Map.tsx
Labels: front-end

#1024 patch: remove bot users from the database
  deployment/docker/entrypoint.sh
Labels: back-end

#1025 patch: merge duplicate emails
  deployment/docker/entrypoint.sh
  django_project/minisass/clean_up_db.py
  django_project/minisass/templates/duplicate_email_merge_notification.html
Labels: back-end

#1026 Merge duplicate emails
  django_project/minisass/clean_up_db.py
Labels: back-end

#1028 add clean db under management/commands directory
  django_project/minisass/management/__init__.py
  django_project/minisass/management/commands/__init__.py
  django_project/minisass/management/commands/clean_up_db.py
Labels: back-end

#1030 patch: check if user profile exists for primary user
  django_project/minisass/management/commands/clean_up_db.py
  django_project/minisass_authentication/views.py
  django_project/minisass_frontend/src/components/AuthenticationButtons/index.tsx
  django_project/minisass_frontend/src/components/EnforcePasswordChange/index.tsx
  django_project/monitor/serializers.py
Labels: back-end

#1033 patch: allow multiple file type extensions
  django_project/monitor/tests/test_observations.py
  django_project/monitor/tests/test_sites.py
Labels: back-end

#1034 patch: fix failing test
  django_project/minisass_authentication/tests/test_views.py
Labels: back-end

#1035 patch: disable test
  deployment/docker/entrypoint.sh
Labels: back-end

#1036 patch: check username directly
  deployment/docker/entrypoint.sh
  django_project/minisass/management/commands/clean_up_db.py
  django_project/minisass_frontend/src/components/Observations/index.tsx
Labels: back-end

#1037 patch: get rid of missing positional arguement
  django_project/monitor/tests/test_observations.py
Labels: back-end

#1038 patch: fix name undefined error
  django_project/monitor/tests/test_observations.py
  django_project/monitor/tests/test_sites.py
Labels: back-end

#1040 patch: gracefully handle null values on user profile
  django_project/minisass_authentication/serializers.py
  django_project/minisass_authentication/views.py
Labels: back-end
