Repository kartoza/miniSASS, pull requests merged in 2024-01, with the labels that each got.

#544 patch: fix observations not found
  django_project/minisass_frontend/src/pages/MainPage/index.tsx
Labels: bug

#537 Manual map page before login
  docs/src/user/manual/map/img/map-1.png
  docs/src/user/manual/map/img/map-10.png
  docs/src/user/manual/map/img/map-11.png
  docs/src/user/manual/map/img/map-12.png
  docs/src/user/manual/map/img/map-13.png
  docs/src/user/manual/map/img/map-2.png
  docs/src/user/manual/map/img/map-3.png
  docs/src/user/manual/map/img/map-4.png
  docs/src/user/manual/map/img/map-5.png
  docs/src/user/manual/map/img/map-6.png
  docs/src/user/manual/map/img/map-7.png
  docs/src/user/manual/map/img/map-8.png
  docs/src/user/manual/map/img/map-9.png
  docs/src/user/manual/map/map.md
Labels: Size: 8, Documentation

#564 Update profile manual
  docs/src/user/manual/user-profile/admin.md
  docs/src/user/manual/user-profile/img/admin-1.png
  docs/src/user/manual/user-profile/img/admin-2.png
  docs/src/user/manual/user-profile/img/recent-activity-10.png
  docs/src/user/manual/user-profile/img/recent-activity-11.png
  docs/src/user/manual/user-profile/img/recent-activity-2.png
  docs/src/user/manual/user-profile/img/recent-activity-3.png
  docs/src/user/manual/user-profile/img/recent-activity-4.png
  docs/src/user/manual/user-profile/img/recent-activity-5.png
  docs/src/user/manual/user-profile/img/recent-activity-6.png
  docs/src/user/manual/user-profile/img/recent-activity-7.png
  docs/src/user/manual/user-profile/img/recent-activity-8.png
  docs/src/user/manual/user-profile/img/recent-activity-9.png
  docs/src/user/manual/user-profile/index.md
  docs/src/user/manual/user-profile/recent-activity.md
Labels: Size: 8, Documentation

#559 patch: adjust cursor style on select site on map
  django_project/minisass_frontend/src/components/Map/Map.tsx
Labels: UI

#569 patch: improve text area styling
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
Labels: UI

#561 patch: retry fetch when 404 is returned
  django_project/minisass_frontend/src/components/ObservationDetails/index.tsx
Labels: front-end

#558 patch: use arrow icons on mobile view
  django_project/minisass_frontend/src/pages/MainPage/index.tsx
Labels: UI

#546 Make home page responsive
  django_project/minisass_frontend/src/components/AuthenticationButtons/index.tsx
  django_project/minisass_frontend/src/pages/MainPage/index.tsx
Labels: UI

#547 Images placeholder on observations
  django_project/minisass_frontend/src/components/ObservationDetails/index.tsx
  django_project/minisass_frontend/static/images/images_placeholder.png
Labels: front-end

#579 patch: update variable names
  django_project/minisass_frontend/src/pages/MainPage/index.tsx
Labels: front-end

#549 patch: add a horizontal scroll to the observation tabs
  django_project/minisass_frontend/src/components/TabbedContent/index.tsx
Labels: UI

#560 patch: set selected site value
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
Labels: front-end

#566 Improve homepage slideshow
  django_project/minisass_frontend/package-lock.json
  django_project/minisass_frontend/package.json
  django_project/minisass_frontend/src/components/SlideShow/index.tsx
Labels: UI

#548 patch: update registration ui
  django_project/minisass_frontend/src/components/RegistrationFormModal/index.tsx
Labels: UI

#594 patch: trim how to page title section
  django_project/minisass_frontend/src/pages/Howto/index.tsx
Labels: front-end

#595 feat: add collapsible titles
  django_project/minisass_frontend/src/components/ObservationDetails/index.tsx
Labels: UI

#596 patch: remove aws partner logo
  django_project/minisass_frontend/src/components/Footer/index.tsx
Labels: UI

#534 Update landing manual
  docs/src/user/manual/img/landing-page-1.png
  docs/src/user/manual/img/landing-page-13.png
  docs/src/user/manual/img/landing-page-20.png
  docs/src/user/manual/img/landing-page-21.png
  docs/src/user/manual/img/landing-page-22.png
  docs/src/user/manual/img/landing-page-23.png
  docs/src/user/manual/img/landing-page-24.png
  docs/src/user/manual/img/landing-page-5.png
  docs/src/user/manual/img/landing-page-6.png
  docs/src/user/manual/img/naming_convention.README
  docs/src/user/manual/landing-page.md
Labels: Size: 5, Documentation

#573 Manual use existing site
  docs/src/user/manual/map/img/map-14.png
  docs/src/user/manual/map/img/map-15.png
  docs/src/user/manual/map/img/map-16.png
  docs/src/user/manual/map/img/map-17.png
  docs/src/user/manual/map/img/map-18.png
  docs/src/user/manual/map/img/map-19.png
  docs/src/user/manual/map/img/map-20.png
  docs/src/user/manual/map/img/map-21.png
  docs/src/user/manual/map/img/map-22.png
  docs/src/user/manual/map/img/map-23.png
  docs/src/user/manual/map/img/map-24.png
  docs/src/user/manual/map/map.md
  docs/src/user/manual/upload/add-records.md
  docs/src/user/manual/upload/img/add-record-1.png
  docs/src/user/manual/upload/img/add-record-10.png
  docs/src/user/manual/upload/img/add-record-11.png
  docs/src/user/manual/upload/img/add-record-12.png
  docs/src/user/manual/upload/img/add-record-13.png
  docs/src/user/manual/upload/img/add-record-14.png
  docs/src/user/manual/upload/img/add-record-15.png
  docs/src/user/manual/upload/img/add-record-16.png
  docs/src/user/manual/upload/img/add-record-17.png
  docs/src/user/manual/upload/img/add-record-18.png
  docs/src/user/manual/upload/img/add-record-2.png
  docs/src/user/manual/upload/img/add-record-3.png
  docs/src/user/manual/upload/img/add-record-4.png
  docs/src/user/manual/upload/img/add-record-5.png
  docs/src/user/manual/upload/img/add-record-6.png
  docs/src/user/manual/upload/img/add-record-7.png
  docs/src/user/manual/upload/img/add-record-8.png
  docs/src/user/manual/upload/img/add-record-9.png
  docs/src/user/manual/upload/img/score-1.png
  docs/src/user/manual/upload/img/score-2.png
  docs/src/user/manual/upload/img/score-3.png
  docs/src/user/manual/upload/img/score-4.png
  docs/src/user/manual/upload/img/score-5.png
  docs/src/user/manual/upload/img/score-6.png
  docs/src/user/manual/upload/img/score-7.png
  docs/src/user/manual/upload/score.md
Labels: Size: 5, Documentation

#587 Add doc for the recent observation
  docs/src/user/manual/landing-page.md
  docs/src/user/manual/map/img/recent-observation-1.png
  docs/src/user/manual/map/img/recent-observation-2.png
  docs/src/user/manual/map/img/recent-observation-3.png
  docs/src/user/manual/map/img/recent-observation-4.png
  docs/src/user/manual/map/img/recent-observation-5.png
  docs/src/user/manual/map/recent-observation.md
Labels: Documentation

#581 Authenticate with email
  django_project/minisass/settings.py
  django_project/minisass_authentication/backends.py
  django_project/minisass_authentication/tests/test_views.py
  django_project/minisass_authentication/urls.py
  django_project/minisass_authentication/views.py
  django_project/minisass_frontend/src/components/AuthenticationButtons/index.tsx
  django_project/minisass_frontend/src/components/LoginFormModal/index.tsx
  django_project/minisass_frontend/src/components/RegistrationFormModal/index.tsx
  django_project/monitor/tests/test_observations.py
Labels: front-end, back-end

#608 Change image upload implementation
  django_project/minisass_frontend/src/components/ManageImagesModal/index.tsx
  django_project/minisass_frontend/src/components/ScoreForm/index.tsx
  django_project/minisass_frontend/src/components/UploadFormModal/index.tsx
  django_project/monitor/observation_views.py
  django_project/monitor/tests/test_download_observation.py
  django_project/monitor/tests/test_observations.py
  django_project/monitor/urls.py
Labels: front-end, back-end

#635 patch: prevent not null constraint
  django_project/monitor/observation_views.py
Labels: back-end

#653 feat: disable buttons if checkbox is unchecked
  django_project/minisass_frontend/src/components/ScoreForm/index.tsx
Labels: front-end

#654 patch: populate sites field with selected site value
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
Labels: front-end

#655 feat: prevent proceeding to next form if mandatory fields are empty
  django_project/minisass_frontend/src/components/CoordinatesInputForm/degreeInputs.tsx
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
Labels: front-end

#656 patch: prevent observation panel from closing
  django_project/minisass_frontend/src/components/TabbedContent/index.tsx
  django_project/minisass_frontend/src/pages/Map/index.tsx
Labels: front-end

#658 patch: add horizontal scroll to multiple tabs
  django_project/minisass_frontend/src/components/TabbedContent/index.tsx
Labels: front-end

#665 patch: add missing group
  django_project/monitor/observation_views.py
Labels: back-end

#663 patch: add character limit migrations
  django_project/monitor/migrations/0007_alter_observationpestimage_image_and_more.py
  django_project/monitor/models.py
Labels: back-end

#668 patch: fix selected image not showing
  django_project/minisass_frontend/src/components/UploadFormModal/index.tsx
Labels: front-end

#670 patch: add fallback authenticator
  django_project/minisass/settings.py
Labels: back-end

#673 patch: save site id when select on map is enabled
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
Labels: front-end

#674 patch: test recent observation fix
  django_project/minisass_frontend/src/pages/MainPage/index.tsx
Labels: front-end

#677 enforce unique site names
  django_project/monitor/observation_views.py
Labels: back-end

#676 patch: prevent site details undefined error
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
Labels: front-end

#679 patch: prevent map reset when close observation details
  django_project/minisass_frontend/src/components/ObservationDetails/index.tsx
Labels: front-end

#675 Manual admin panel
  docs/src/administrator/django-admin.md
  docs/src/administrator/img/django-admin-1.png
  docs/src/administrator/img/django-admin-10.png
  docs/src/administrator/img/django-admin-11.png
  docs/src/administrator/img/django-admin-12.png
  docs/src/administrator/img/django-admin-13.png
  docs/src/administrator/img/django-admin-14.png
  docs/src/administrator/img/django-admin-15.png
  docs/src/administrator/img/django-admin-16.png
  docs/src/administrator/img/django-admin-17.png
  docs/src/administrator/img/django-admin-2.png
  docs/src/administrator/img/django-admin-3.png
  docs/src/administrator/img/django-admin-4.png
  docs/src/administrator/img/django-admin-5.png
  docs/src/administrator/img/django-admin-6.png
  docs/src/administrator/img/django-admin-7.png
  docs/src/administrator/img/django-admin-8.png
  docs/src/administrator/img/django-admin-9.png
Labels: Size: 8, Documentation

#680 patch: fix persisten site details undefined error
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
Labels: front-end

#671 patch: update contact us recipient
  django_project/minisass/settings.py
Labels: back-end

#683 patch: update AI score message
  django_project/minisass_frontend/src/components/ManageImagesModal/index.tsx
Labels: front-end

#684 patch: show minisass logo in registration email
  django_project/minisass_authentication/templates/registration/activate_account.html
  django_project/minisass_authentication/templates/registration/password_reset_email.html
Labels: back-end

#686 Doc minisass section tables
  docs/src/administrator/django-admin.md
  docs/src/administrator/img/django-admin-18.png
  docs/src/administrator/img/django-admin-19.png
  docs/src/administrator/img/django-admin-20.png
  docs/src/administrator/img/django-admin-21.png
  docs/src/administrator/img/django-admin-22.png
  docs/src/administrator/img/django-admin-23.png
Labels: Documentation

#687 patch: update river category description
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
Labels: front-end

#690 Add general doc for admin tables
  docs/src/administrator/django-admin.md
Labels: Size: 1, Documentation

#697 patch: create new observation on existing site
  django_project/minisass_frontend/src/components/ScoreForm/index.tsx
  django_project/monitor/observation_views.py
  django_project/monitor/views.py
Labels: back-end

#704 patch: fix invalid point initialisation error
  django_project/monitor/observation_views.py
Labels: back-end

#713 patch: fix the replace int error
  django_project/monitor/observation_views.py
Labels: back-end

#705 Update the login dev doc
  docs/src/developer/authentication.md
  docs/src/developer/img/login_api.png
Labels: Size: 1, Documentation

#755 patch: prevent dialog appearing after save close
  django_project/minisass_frontend/src/components/ScoreForm/index.tsx
Labels: front-end

#766 patch: return removed dialog
  django_project/minisass_frontend/src/components/DataInputForm/index.tsx
Labels: UI

#751 feat: integrate ai score calculations
  .example.env
  deployment/docker/requirements.txt
  django_project/minisass_frontend/src/components/ManageImagesModal/index.tsx
  django_project/minisass_frontend/src/components/ScoreForm/index.tsx
  django_project/monitor/observation_views.py
Labels: front-end, back-end

#772 patch: surround code in try ,catch
  django_project/monitor/observation_views.py
Labels: back-end

#824 patch: limit tensorflow memory usage
  .example.env
  django_project/minisass/settings.py
  django_project/minisass/tensorflow_memory_limit.py
Labels: back-end

#835 patch: add parsers and create site images endpoint
  django_project/monitor/observation_views.py
  django_project/monitor/site_views.py
  django_project/monitor/urls.py
Labels: back-end

#832 Update footer options
  docs/src/user/manual/how-to/how-to.md
  docs/src/user/manual/how-to/img/how-to-15.png
  docs/src/user/manual/img/landing-page-25.png
  docs/src/user/manual/landing-page.md
  docs/src/user/manual/map/img/map-25.png
  docs/src/user/manual/map/map.md
  docs/src/user/manual/map/recent-observation.md
Labels: Size: 2, Documentation

#861 patch: preserve ml predictions values
  django_project/minisass_frontend/src/components/ScoreForm/index.tsx
Labels: front-end

#866 patch: accommodate multiple image uploads
  django_project/monitor/site_views.py
  django_project/monitor/tests/test_sites.py
Labels: back-end

#867 patch: remove login decorator
  django_project/monitor/observation_views.py
Labels: back-end
